# Copyright (C) 2021 The Android Open Source Project
load("//build/kernel/kleaf:kernel.bzl", "kernel_dtstree")

kernel_dtstree(
    name = "mtk_dt",
    srcs = glob(
        [
            "Makefile",
            "mediatek/Makefile",
            "mediatek/**/*.dtsi",
            "mediatek/**/*.dts",
        ],
        exclude = [
            "**/.*",
            "**/.*/**",
            "**/BUILD.bazel",
            "**/*.bzl",
        ],
    ) + [
         "//kernel_device_modules-6.1:mgk_dt-bindings",
    ],
    visibility = ["//visibility:public"],
)
